/**
 * generate.types.mjs
 *
 * Modes:
 *   - default: repair mode (overwrite the types.d.js file)
 *   - --check: validation mode (no overwrite)
 */

import fs from "fs";
import path from "path";

const MODULES_DIR = path.join(process.cwd(), "modules");
const OUTPUT_FILE = path.join(process.cwd(), "types.d.js");

const isCheckMode = process.argv.includes("--check");

// Input validation.
if (!fs.existsSync(MODULES_DIR)) {
    console.error("❌ ./modules directory does not exist");
    process.exit(1);
}

const files = fs.readdirSync(MODULES_DIR).filter(f => f.endsWith(".cjs"));

if (files.length === 0) {
    console.error("❌ No .cjs files found in ./modules/");
    process.exit(1);
}

// Generate new content for the types.d.js file.
const imports = [];

for (const file of files) {
    const relativePath = `./modules/${file}`;
    const fullPath = path.join(MODULES_DIR, file);
    const content = fs.readFileSync(fullPath, "utf8");

    const classNames = [...content.matchAll(/\bclass\s+([A-Za-z_$][A-Za-z0-9_$]*)\b/g)]
        .map(m => m[1]);

    if (classNames.length === 0) {
        console.warn(`⚠️  No class found in '${relativePath}', skipping`);
        continue;
    }

    if (classNames.length > 1) {
        console.warn(`⚠️  More than one class found in '${relativePath}', skipping`);
        continue;
    }

    imports.push(`/** @typedef {import('${relativePath}')} ${classNames[0]} */`);
}

// Stable output (order matters for diffs).
imports.sort();

const output = `// IMPORTANT: DO NOT MANUALLY EDIT THIS FILE!
// This file is auto generated by the generate-types.cjs tool.
// Simply run this tool when modules have changed.

/**
 * The following makes VSCode understand how to lookup modules so that
 * Cmd+Click on classes and functions makes its navigation feature work.
 */

${imports.join("\n")}
`;

// Compare generated with existing.
const existing = fs.existsSync(OUTPUT_FILE)
    ? fs.readFileSync(OUTPUT_FILE, "utf8")
    : null;

const isDifferent = existing !== output;

if (!isDifferent) {
    console.log("✅ types.d.js is already up to date. No action needed.");
    process.exit(0);
}

if (isCheckMode) {
    console.error("❌ types.d.js is out of date. Run `npm run generate_types` on local dev.");
    process.exit(1);
}

// Repair mode and different content, so write changes.
fs.writeFileSync(OUTPUT_FILE, output, "utf8");

console.log(`✅ types.d.js is regenerated (${imports.length} modules). Commit the changes.`);
process.exit(0);
