/**
 * Understands how to (re)generate the types.d.js file.
 * For each cjs file the modules folder, its creates a typedef import.
 */

import fs from "fs";
import path from "path";

const MODULES_DIR = path.join(process.cwd(), "modules");
const OUTPUT_FILE = path.join(process.cwd(), "types.d.js");

// Read module filenames
const files = fs.readdirSync(MODULES_DIR).filter(f => f.endsWith(".cjs"));

if (files.length === 0) {
    console.error("No .cjs files found in ./modules/");
    process.exit(1);
}

let imports = [];

// Extract class names and generate typedef imports.
for (const file of files) {
    const fullPath = path.join(MODULES_DIR, file);
    const content = fs.readFileSync(fullPath, "utf8");

    // Try to extract "class <Name>"
    const classMatch = content.match(/class\s+([A-Za-z0-9_]+)/);

    if (!classMatch) {
        console.warn(`⚠ No class found in ${file}, skipping`);
        continue;
    }

    const className = classMatch[1];
    const relativePath = `./modules/${file}`;

    imports.push(`/** @typedef {import('${relativePath}')} ${className} */`);
}

// Build final output.
const output = `// IMPORTANT: DO NOT MANUALLY EDIT THIS FILE!
// This file is auto generated by the generate-types.cjs tool.
// Simply run this tool when modules have changed.

/**
 * The following makes VSCode understand how to lookup modules so that 
 * Cmd+Click on classes and functions makes its navigation feature work.
 */

${imports.join("\n")}
`;

fs.writeFileSync(OUTPUT_FILE, output, "utf8");

console.log(`✔ types.d.js generated with ${imports.length} modules.`);
