// IMPORTANT: DO NOT MANUALLY EDIT THIS FILE!
// This file is auto generated by the generate-types.cjs tool.
// Simply run this tool when modules have changed.

/**
 * The following makes VSCode understand how to lookup modules so that
 * Cmd+Click on classes and functions makes its navigation feature work.
 */

/** @typedef {import('./modules/BrandSectionMapResolver.cjs')} BrandSectionMapResolver */
/** @typedef {import('./modules/BrandSectionResolver.cjs')} BrandSectionResolver */
/** @typedef {import('./modules/ExportInDesignArticlesToFolder.cjs')} ExportInDesignArticlesToFolder */
/** @typedef {import('./modules/FileUtils.cjs')} FileUtils */
/** @typedef {import('./modules/FitArticleWithAIService.cjs')} FitArticleWithAIService */
/** @typedef {import('./modules/GenreResolver.cjs')} GenreResolver */
/** @typedef {import('./modules/HttpLogger.cjs')} HttpLogger */
/** @typedef {import('./modules/InDesignArticleService.cjs')} InDesignArticleService */
/** @typedef {import('./modules/Logger.cjs')} Logger */
/** @typedef {import('./modules/PageLayoutSettings.cjs')} PageLayoutSettings */
/** @typedef {import('./modules/PlaService.cjs')} PlaService */
/** @typedef {import('./modules/PreferencesManager.cjs')} PreferencesManager */
/** @typedef {import('./modules/RegenerateArticleShapesService.cjs')} RegenerateArticleShapesService */
/** @typedef {import('./modules/Settings.cjs')} Settings */
/** @typedef {import('./modules/StudioJsonRpcClient.cjs')} StudioJsonRpcClient */
/** @typedef {import('./modules/VersionUtils.cjs')} VersionUtils */
