// IMPORTANT: DO NOT MANUALLY EDIT THIS FILE!
// This file is auto generated by the generate-types.mjs tool.
// Simply run this tool when modules have changed.

/**
 * The following makes VSCode understand how to lookup modules so that 
 * Cmd+Click on classes and functions makes its navigation feature work.
 */

/** @typedef {import('./modules/BrandSectionMapResolver.mjs')} BrandSectionMapResolver */
/** @typedef {import('./modules/Errors.mjs')} ArgumentError */
/** @typedef {import('./modules/ExportInDesignArticlesToFolder.mjs')} ExportInDesignArticlesToFolder */
/** @typedef {import('./modules/FileUtils.mjs')} FileUtils */
/** @typedef {import('./modules/FitArticleWithAIService.mjs')} FitArticleWithAIService */
/** @typedef {import('./modules/GenreResolver.mjs')} GenreResolver */
/** @typedef {import('./modules/HttpLogger.mjs')} HttpLogger */
/** @typedef {import('./modules/InDesignArticleService.mjs')} InDesignArticleService */
/** @typedef {import('./modules/Logger.mjs')} Logger */
/** @typedef {import('./modules/PageLayoutSettings.mjs')} PageLayoutSettings */
/** @typedef {import('./modules/PlaService.mjs')} PlaService */
/** @typedef {import('./modules/PreferencesManager.mjs')} PreferencesManager */
/** @typedef {import('./modules/RegenerateArticleShapesService.mjs')} RegenerateArticleShapesService */
/** @typedef {import('./modules/Settings.mjs')} Settings */
/** @typedef {import('./modules/StudioJsonRpcClient.mjs')} StudioJsonRpcClient */
/** @typedef {import('./modules/VersionUtils.mjs')} VersionUtils */
